name: RedRealms
version: 0.1.0
main: org.concordiacraft.redrealms.main.RedRealms
api-version: 1.13
authors:
  - Theorenter
  - Nicekita
softdepend: [RedUtils]
commands:
  menu:
    description: "Открыть внутриигровое меню"
    usage: /menu
  profile:
    description: "Октрыть меню личного профиля"
    usage: /profile
  town:
    description: "Открыть меню взаимодействия с Вашим городом"
    usage: /town
  realm:
    description: "Открыть меню взаимодействия с Вашей державой"
    usage: /realm
