name: RedRealms
version: 0.1.0
main: org.concordiacraft.redrealms.main.RedRealms
api-version: 1.13
authors:
  - Theorenter
  - Nicekita
softdepend: [RedUtils, TheNewEconomy]
commands:
  menu:
    description: "Открыть внутриигровое меню"
    usage: /menu
  profile:
    description: "Октрыть меню личного профиля"
    usage: /profile
  town:
    description: "Открыть информацию связанную с городами"
    usage: /town
  admin:
    description: "Админ-управление"
    usage: /admin
  chunk:
    description: "Управление чанками"
    usage: /chunk