name: RedRealms
version: 0.1.0
main: org.concordiacraft.redrealms.main.RedRealms
api-version: 1.13
authors:
  - Theorenter
  - Nicekita
softdepend: [RedUtils]
commands:
  towncreate:
    description: 'Create a new camp'
    usage: /towncreate <name>
  addchunk:
    description: 'Adds Chunk to Currently existing realm'
    usage: /addchunk
  region:
    description: 'Adds interaction with regions'
    usage: /region add  adds chunk you are standing on. /region create <name>