language: russian
author: Theorenter

############################################################
# +------------------------------------------------------+ #
# |   Назначение цветов                                  | #
# +------------------------------------------------------+ #
############################################################

components-color:
  help: "#0092FC"
  conversation-text: "#A5ACB8"

############################################################
# +------------------------------------------------------+ #
# |   Типы биомов                                        | #
# +------------------------------------------------------+ #
############################################################

biomes:
  snowy-biome: "Снежный биом"
  cold-biome: "Холодный биом"
  temperate-biome: "Умеренный биом"
  warm-biome: "Тёплый биом"

############################################################
# +------------------------------------------------------+ #
# |   Сообщения                                          | #
# +------------------------------------------------------+ #
############################################################

messages:

  errors:
    only-for-players: "Данная команда доступна только игрокам на сервере!"
    don't-have-permissions-to-do: "΃ У Вас недостаточно прав для выполнения данного действия!"
    don't-have-permissions-command: "΃ У Вас недостаточно прав для использования данной команды!"

    this-name-too-short: "΃ Название слишком короткое. Мин.длина — <#FDAEE0><bold>%s"
    this-name-too-long: "΃ Название слишком длинное. Макс.длина — <#FDAEE0><bold>%s"
    this-name-out-of-regex: "΃ Название города некорректно: можно использовать только цифры, буквы русского алфавита, тире и нижнее подчёркивание вместо пробела!"
    this-town-name-already-taken: "΃ К сожалению, город с таким названием уже существует, выберите другое!"
    this-territory-already-taken: "΃ Этот участок уже принадлежит городу <#FDAEE0><bold>%s<#FFFFFF>!"
    this-biome-type-unavailable: "΃ Вы не можете основать поселение на данном типе биома, выберите другой чанк."
    create-town-in-unavailable-world: "΃ Вы не можете создать новый город в этом мире!"
    private-territory-break: "΃ Вы не можете разрушать блоки на этой территории!"
    player-in-prompt: "΃ Вы не можете произвести какие-либо дейтсвия, т.к. сервер ожидает от Вас запрос в чате!"

    invalid-length-arguments: "΃ Команда введена неверно: вы указали некорректное количество аргументов!"
    player-not-in-town: "΃ Вы не состоите ни в одном городе!"
    player-is-not-mayor: "΃ Вы должны являться мэром города, чтобы сделать это!"
    player-not-on-the-server: "΃ Игрока <#FDAEE0><bold>%s<#FFFFFF> нет на сервере!"
    player-already-in-town: "΃ Вы уже состоите в городе \"<#FDAEE0><bold>%s<#FFFFFF>\", сначала покиньте его, чтобы основать новое поселение!"
    another-player-already-in-town: "΃ Игрок <#FDAEE0><bold>%s<#FFFFFF> уже состоит в городе \"<#FDAEE0><bold>%s<#FFFFFF>\"!"
    has-not-invited: "΃ У Вас нет ни одного приглашения!"

    dont't-have-tech-to-craft: "΃ Вы не имеете нужной технологии, чтобы создать <#FDAEE0><bold>%s<#FFFFFF>!"
    dont't-have-tech-to-use: "΃ Вы не имеете нужной технологии, чтобы использовать <#FDAEE0><bold>%s<#FFFFFF>!"

    cannot-create-town-here: "΃ Вы не можете основать свой город здесь: города нельзя основывать на морских территориях!"

  notifications:
    prompt-data-item-back: "΁ Вам был возвращён следующий предмет: %s<reset>."
    prompt-data-item-back-inventory-full: " т.к. Ваш инвентарь полон, предмет появился возле Вас."
    town-creation-after-invalid: "Теперь укажите в чате корректное название города ΢"
    new-town-was-created: "΁ Игрок <#FDAEE0><bold>%s<#FFFFFF> основал новый город — <#FDAEE0><bold>%s"
    new-town-was-created-by-you: "΁ Вы основали новый город, который будет носить название \"<#FDAEE0><bold>%s<#FFFFFF>\"."
    town-was-deserted: "΁ Город \"<#FDAEE0><bold>%s<#FFFFFF>\" был распущен, т.к. в нём не осталось граждан."
    you-were-invited-town: "΁ Игрок <#FDAEE0><bold>%s<#FFFFFF> пригласил Вас в город \"<#FDAEE0><bold>%s<#FFFFFF>\" Хотите ли Вы присоединиться?"

  help:
    town:
      1: "<#ffffff>Команды взаимодействия с <#FDAEE0><bold>городом:"
      2: "<#FDAEE0><bold>/town menu <#AAAAAA>— <#ffffff>Открыть меню города."
      3: "<#FDAEE0><bold>/town leave <#AAAAAA>— <#ffffff>Покинуть свой текущий город."
      4: "<#FDAEE0><bold>/town invite [Имя игрока] <#AAAAAA>— <#ffffff>Пригласить игрока в город (только для мэра)."

  active-text:
    accept: "<#55FF55><bold>Принять<reset>"
    deny: "<#D42625><bold>Отказать<reset>"

############################################################
# +------------------------------------------------------+ #
# |   Персонажи и сообщения переписки                    | #
# +------------------------------------------------------+ #
############################################################

conversations:

  name-preformat: "΀ <#EFEFEF><bold>"
  space: "              "

  characters:
    consul:
      portrait: "΂"
      name: "Консул Марий"

  prompts:
    consul:
      cannot-create-town-there:
        1: "<#A5ACB8>Мессер, нет, здесь город не построишь!"
        2: "<#A5ACB8>Выбери приемлимый биом: горы, поля"
        3: "<#A5ACB8>леса, пустыню или тундру, но не это!"

    town-create-start:
      snowy: "<#FFFFFF> — неплодородное и суровое место, но прекрасный выбор для тех, кто хочет вести кочевой образ жизни."
      cold: "<#FFFFFF> — место с мёрзлой почвой, большими лесами и горами. Прекрасно для ремесленных городков."
      temperate: "<#FFFFFF> — плодородные земли, обширные поля и леса; подходящее место как для крупных мегаполисов, так и для малых городков."
      warm: "<#FFFFFF> — неплодородные высохшие земли, но зачастую имеющие в себе много минеральных богатств. Здесь выйдет хорошее поселение для шахтёров и алхимиков."
      prompt: "΁ <#FFFFFF>Укажите в чате название Вашего города ΢"
      hover-snowy: "TODO описание особеностей снежного биома"
      hover-cold: "TODO описание особеностей холодного биома"
      hover-temperate: "TODO описание особеностей умеренного биома"
      hover-warm: "TODO описание особеностей тёплого биома"

############################################################
# +------------------------------------------------------+ #
# |   GUIs                                               | #
# +------------------------------------------------------+ #
############################################################

gui:
  menu:
    profile:
      name: "<#FDAEE0><bold>Профиль"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    town:
      name: "<#FDAEE0><bold>Город"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    realm:
      name: "<#FDAEE0><bold>Держава"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    fraction:
      name: "<#FF5555><bold>Фракция ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    market:
      name: "<#FF5555><bold>Рынок ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    encyclopedia:
      name: "<#FF5555><bold>Энциклопедия ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"

    locked-lore-1: "<#B57072>Данная игровая механика"
    locked-lore-2: "<#B57072>и раздел будут добавлены"
    locked-lore-3: "<#B57072>в последующих обновлениях."