language: russian
author: Theorenter

############################################################
# +------------------------------------------------------+ #
# |   Назначение цветов                                  | #
# +------------------------------------------------------+ #
############################################################

components-color:
  help: "#0092FC"
  conversation-text: "#C3D7E5"

############################################################
# +------------------------------------------------------+ #
# |   Типы биомов                                        | #
# +------------------------------------------------------+ #
############################################################

biomes:
  snowy-biome: "Снежный биом"
  cold-biome: "Холодный биом"
  temperate-biome: "Умеренный биом"
  warm-biome: "Тёплый биом"

############################################################
# +------------------------------------------------------+ #
# |   Сообщения                                          | #
# +------------------------------------------------------+ #
############################################################

messages:

  errors:
    only-for-players: "Данная команда доступна только игрокам на сервере!"
    dont-have-permissions-to-do: "<#D82625>⚠ <reset>У Вас недостаточно прав для выполнения данного действия!"
    dont-have-permissions-command: "<#D82625>⚠ <reset>У Вас недостаточно прав для использования данной команды!"

    this-name-too-short: "΃ Название слишком короткое. Мин.длина - %s"
    this-name-too-long: "΃ Название слишком длинное. Макс.длина - %s"
    this-name-out-of-regex: "΃ Название города некорректно: можно использовать только цифры, буквы русского алфавита и нижнее подчёркивание!"
    this-town-name-already-taken: "΃ К сожалению, город с таким названием уже существует, выберите другое!"
    this-territory-already-taken: "΃ На данном участке уже существует другое поселение!"
    private-territory-break: "΃ Вы не можете разрушать блоки на этой территории!"
    player-in-prompt: "΃ Вы не можете произвести какие-либо дейтсвия, т.к. сервер ожидает от Вас запрос в чате!"

  notifications:
    prompt-data-item-back: "΁ Вам был возвращён следующий предмет: %s<reset>."
    prompt-data-item-back-inventory-full: " т.к. Ваш инвентарь полон, предмет появился возле Вас."
    town-creation-after-invalid: "΁ Теперь укажите в чате корректное название города."

############################################################
# +------------------------------------------------------+ #
# |   Персонажи и сообщения переписки                    | #
# +------------------------------------------------------+ #
############################################################

conversations:

  name-preformat: "΀ <#EFEFEF><bold>"
  space: "              "

  characters:
    consul:
      portrait: "΂"
      name: "Консул Марий"

  prompts:
    consul:
      cannot-create-town-there:
        1: "<#C3D7E5>Мессер, нет, здесь город не построишь!"
        2: "<#C3D7E5>Выбери приемлимый биом: горы, поля"
        3: "<#C3D7E5>леса, пустыню или тундру, но не это!"

      town-create-start:
        1: "%s - Интересный выбор. От"
        2: "<#C3D7E5>этого многое будет зависеть. А теперь"
        3: "<#C3D7E5>скажи, как ты хочешь назвать город?"
        hover-snowy: "TODO описание особеностей снежного биома"
        hover-cold: "TODO описание особеностей холодного биома"
        hover-temperate: "TODO описание особеностей умеренного биома"
        hover-warm: "TODO описание особеностей тёплого биома"