language: russian
author: Theorenter

############################################################
# +------------------------------------------------------+ #
# |   Назначение цветов                                  | #
# +------------------------------------------------------+ #
############################################################

components-color:
  help: "#0092FC"
  conversation-text: "#A5ACB8"

############################################################
# +------------------------------------------------------+ #
# |   Типы биомов                                        | #
# +------------------------------------------------------+ #
############################################################

biomes:
  snowy-biome: "Снежный биом"
  cold-biome: "Холодный биом"
  temperate-biome: "Умеренный биом"
  warm-biome: "Тёплый биом"

############################################################
# +------------------------------------------------------+ #
# |   Сообщения                                          | #
# +------------------------------------------------------+ #
############################################################

messages:

  errors:
    only-for-players: "Данная команда доступна только игрокам на сервере!"
    dont-have-permissions-to-do: "<#D82625>⚠ <reset>У Вас недостаточно прав для выполнения данного действия!"
    dont-have-permissions-command: "<#D82625>⚠ <reset>У Вас недостаточно прав для использования данной команды!"

    this-name-too-short: "΃ Название слишком короткое. Мин.длина - %s"
    this-name-too-long: "΃ Название слишком длинное. Макс.длина - %s"
    this-name-out-of-regex: "΃ Название города некорректно: можно использовать только цифры, буквы русского алфавита, тире и нижнее подчёркивание вместо пробела!"
    this-town-name-already-taken: "΃ К сожалению, город с таким названием уже существует, выберите другое!"
    this-territory-already-taken: "΃ На данном участке уже существует другое поселение!"
    private-territory-break: "΃ Вы не можете разрушать блоки на этой территории!"
    player-in-prompt: "΃ Вы не можете произвести какие-либо дейтсвия, т.к. сервер ожидает от Вас запрос в чате!"

  notifications:
    prompt-data-item-back: "΁ Вам был возвращён следующий предмет: %s<reset>."
    prompt-data-item-back-inventory-full: " т.к. Ваш инвентарь полон, предмет появился возле Вас."
    town-creation-after-invalid: "Теперь укажите в чате корректное название города."
    new-town-was-created: "΁ Игрок %s основал новый город - %s"

############################################################
# +------------------------------------------------------+ #
# |   Персонажи и сообщения переписки                    | #
# +------------------------------------------------------+ #
############################################################

conversations:

  name-preformat: "΀ <#EFEFEF><bold>"
  space: "              "

  characters:
    consul:
      portrait: "΂"
      name: "Консул Марий"

  prompts:
    consul:
      cannot-create-town-there:
        1: "<#A5ACB8>Мессер, нет, здесь город не построишь!"
        2: "<#A5ACB8>Выбери приемлимый биом: горы, поля"
        3: "<#A5ACB8>леса, пустыню или тундру, но не это!"

      town-create-start:
        1: "%s - Интересный выбор. От"
        2: "<#A5ACB8>этого многое будет зависеть. А теперь"
        3: "<#A5ACB8>скажи, как ты хочешь назвать город?"
        hover-snowy: "TODO описание особеностей снежного биома"
        hover-cold: "TODO описание особеностей холодного биома"
        hover-temperate: "TODO описание особеностей умеренного биома"
        hover-warm: "TODO описание особеностей тёплого биома"

############################################################
# +------------------------------------------------------+ #
# |   GUIs                                               | #
# +------------------------------------------------------+ #
############################################################

gui:
  menu:
    profile:
      name: "<#FDAEE0><bold>Профиль"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    town:
      name: "<#FDAEE0><bold>Город"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    realm:
      name: "<#FDAEE0><bold>Держава"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    fraction:
      name: "<#FF5555><bold>Фракция ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    market:
      name: "<#FF5555><bold>Рынок ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"
    encyclopedia:
      name: "<#FF5555><bold>Энциклопедия ΋"
      lore-1: "<#A5ACB8>Посмотрите здесь всю информацию"
      lore-2: "<#A5ACB8>о себе на сервере."
      lore-3: "<#0092FC> → *Клик* - открыть меню"

    locked-lore-1: "<#B57072>Данная игровая механика"
    locked-lore-2: "<#B57072>и раздел будут добавлены"
    locked-lore-3: "<#B57072>в последующих обновлениях."