name: RedRealms
version: 0.1.0.0
main: org.concordacraft.redrealms.main.RedRealms
api-version: 1.13
authors:
  - Theorenter
  - Nicekita
commands:
  campcreate:
    description: 'Create a new camp'
    usage: /campcreate <name>
  addchunk:
    description: 'Adds Chunk to Currently existing realm'
    usage: /addchunk