############################################################
# +------------------------------------------------------+ #
# |            RedRealms Configuration File              | #
# +------------------------------------------------------+ #
############################################################

# The language file you wish to use
language: english.yml

############################################################
# +------------------------------------------------------+ #
# |                 Plugin interfacing                   | #
# +------------------------------------------------------+ #
############################################################

plugin:
  # Track all plugin actions that will be displayed in the console
  debug: true